# Dockerfile for Node.js application
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./
COPY package-lock.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of the Node.js application code
COPY . .

# Build the Next.js application
#RUN npm run build

# Expose the port that the Node.js application will run on
EXPOSE 3001

# Start the Next.js application
CMD ["npm", "run","dev"]